version: '3.7'
services:
  mongodb_service:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_service_data_volume:/data/db

volumes:
  mongodb_service_data_volume: